[info]
listen_host = "localhost"
listen_port = 3338
url = "https://mint.hashpool.dev"
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"

[info.http_cache]
backend = "memory"
ttl = 60
tti = 60

[mint_info]
name = "Hashpool Mint"
description = "cashu mint to expose ehash and ecash operations to end user wallets"

[database]
engine = "sqlite"

[ln]
ln_backend = "fakewallet"
min_mint = 1
max_mint = 500000
min_melt = 1
max_melt = 500000

[fake_wallet]
supported_units = ["sat", "HASH"]
fee_percent = 0.02
reserve_fee_min = 2
# These two have defaults, but we'll include them explicitly for clarity
# min_delay_time = 1
# max_delay_time = 3

[hashpool_mint]
db_path = ".devenv/state/mint/mint.sqlite"

