# Braiins Pool Upstream Connection
# upstream_authority_pubkey = "u95GEReVMjK6k5YqiSFNqqTnKU4ypU2Wm8awa6tmbmDmk1bWt"
# upstream_address = "18.196.32.109"
# upstream_port = 3336

# Local SRI JDC Upstream Connection
upstream_address = "127.0.0.1"
upstream_port = 34254
upstream_authority_pubkey = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"

# Local Mining Device Downstream Connection
# Dev - use your local network IP or 0.0.0.0 to listen on all interfaces
# downstream_address = "0.0.0.0"
# downstream_port = 34255
# Prod - VPS external IP
downstream_address = "188.40.233.11"
downstream_port = 34256

# Redact miner IP addresses from database and website (prod)
redact_ip = true

# Faucet configuration
faucet_port = 8083
faucet_timeout = 3

# Version support
max_supported_version = 2
min_supported_version = 2

# Minimum extranonce2 size for downstream
# Max value: 16 (leaves 0 bytes for search space splitting of downstreams)
# Max value for CGminer: 8
# Min value: 2
min_extranonce2_size = 8

# Stats server config
stats_server_address = "127.0.0.1:4001"

# Difficulty params
[downstream_difficulty_config]
# target number of shares per minute the miner should be sending
# Note: min_individual_miner_hashrate is automatically calculated from
# minimum_difficulty in shared config to ensure all shares earn ehash
shares_per_minute = 6.0

[upstream_difficulty_config]
# interval in seconds to elapse before updating channel hashrate with the pool
channel_diff_update_interval = 60
# estimated accumulated hashrate of all downstream miners (e.g.: 10 Th/s = 10_000_000_000_000.0)
channel_nominal_hashrate = 10_000_000.0

[wallet]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
db_path = ".devenv/state/translator/wallet.sqlite"
locking_privkey = "e1c193b1a2681f01a10731f317c754a031ed9e61aaaf702b5083e55a2c0a8fff"
